language: node_js
node_js: node
dist: trusty
cache:
  directories:
    - node_modules
    - "$HOME/.electron"
    - "$HOME/.cache"
install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - yarn install
script:
  - yarn run compile
